### ISSUE TITLE
Anisotropy rounding

### ISSUE THREAD

**Issue by manerotoni** [embl-cba/cats#30]
the software compute the anisotropy in XYZ. I wonder if it should 
not round the results after a certain level. 
In my case I have images with anisotropy settings  0.99999999305.
If it consider this as 1 and does not transform the image it is ok. The problem is 
if CATS try to make the image isotropic.

**Comment by tischi** [comment]
@manerotoni I checked the code and it does a rounding when deciding to compensate for the anisotropy:

```
           binning[2] = (int) Math.ceil( binFactor / anisotropy );
            if( binning[2]==0 ) binning[2] = 1;
```

So that seems fine.
